# Generated by Django 2.0.3 on 2018-04-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180402_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='relates_to',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
