# Generated by Django 2.0.3 on 2018-04-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180403_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='relates_to',
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
