# Generated by Django 2.0.3 on 2018-04-02 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180401_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='iD',
            field=models.CharField(default=uuid.UUID('681c23cb-28d2-4abe-bab5-6da8f7aec641'), max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='relates_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='iD',
            field=models.CharField(default=uuid.UUID('4ff9253f-bdaa-44d2-87bc-0e42abb2948c'), max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='relates_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
