# Generated by Django 2.0.3 on 2018-04-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180403_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collab',
            field=models.CharField(default='', max_length=250),
        ),
    ]
