# Generated by Django 2.0.3 on 2018-04-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180402_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='iD',
        ),
        migrations.RemoveField(
            model_name='task',
            name='iD',
        ),
    ]
