# Generated by Django 2.0.3 on 2018-04-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20180402_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='relates_to',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='task',
            name='relates_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
